name: ci

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@master
              with:
                  # Make sure the actual branch is checked out when running on pull requests
                  ref: ${{ github.head_ref }}
            - name: Validate format
              uses: creyD/prettier_action@v2.2
              with:
                  dry: true
            - name: Install Deno
              uses: denolib/setup-deno@master
              with:
                  deno-version: 0.36.0
            - name: Unit tests
              run: make run-tests
